name: 'my_itsm_dbt_project'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
snapshot-paths: ["snapshots"]

models:
  my_itsm_dbt_project:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
